list1 = [        
    "1. The role of respect in romantic relationships.",
    "2. Romantic weekend getaways: Planning the perfect trip.",
    "3. The concept of \"puppy love.\"",
    "4. The impact of romantic expectations on relationship satisfaction.",
    "5. The portrayal of love triangles in literature and film.",
    "6. The role of commitment in maintaining a relationship.",
    "7. The influence of romanticism on personal philosophy.",
    "8. The impact of gender roles on romantic expectations.",
    "9. The portrayal of romance in superhero films.",
    "10. The concept of \"romantic commitment issues.\"",
    "11. The role of fantasy in romantic relationships.",
    "12. The influence of childhood fairy tales on romantic ideals.",
    "13. The portrayal of polyamorous relationships in media.",
    "14. The concept of \"co-dependency\" in romance.",
    "15. The role of gifts in expressing love.",
    "16. The impact of sexual orientation on romantic experiences.",
    "17. The portrayal of romance in epic poetry.",
    "18. The concept of \"first kiss\" significance.",
    "19. The role of holiday traditions in romantic relationships.",
    "20. The influence of literary love stories on real-life relationships.",
    "21. The portrayal of long-term commitment in movies.",
    "22. The concept of \"emotional intimacy.\"",
    "23. The role of surprise dates in keeping romance alive.",
    "24. The impact of social media on breakups.",
    "25. The portrayal of unconventional marriage proposals in media.",
    "26. The concept of \"love and lust.\"",
    "27. The role of fashion and appearance in romantic attraction.",
    "28. The influence of romantic literature on society's view of love.",
    "29. The portrayal of \"love at first sight\" in different cultures.",
    "30. The concept of \"relationship goals.\"",
    "31. The role of art in expressing romantic feelings.",
    "32. The impact of financial disagreements on relationships.",
    "33. The portrayal of romantic villains in media.",
    "34. The concept of \"romantic rivalry.\"",
    "35. The role of cooking and food in romance.",
    "36. The influence of romantic comedy tropes on dating.",
    "37. The portrayal of \"bad boy\" and \"bad girl\" archetypes in romance.",
    "38. The concept of \"love letters\" in the digital age.",
    "39. The role of storytelling in romantic bonding.",
    "40. The impact of lifestyle choices on romantic compatibility.",
    "41. The portrayal of romance in graphic novels.",
    "42. The concept of \"relationship anxiety.\"",
    "43. The role of shared hobbies in strengthening relationships.",
    "44. The influence of travel on romantic perspectives.",
    "45. The portrayal of romantic suspense in literature.",
    "46. The concept of \"honeymoon destinations.\"",
    "47. The role of pets in romantic relationships.",
    "48. The impact of moving in together on a relationship.",
    "49. The portrayal of secret relationships in media.",
    "50. The concept of \"romantic superstitions.\"",
    "",
    "### Romantic Cultural and Historical Perspectives",
    "51. The role of courtship rituals in different cultures.",
    "52. The influence of romantic poetry on cultural perceptions of love.",
    "53. The portrayal of romance in ancient mythology.",
    "54. The concept of \"romantic heroism\" in classic literature.",
    "55. The role of arranged marriages in different cultures.",
    "56. The impact of historical events on romantic norms.",
    "57. The portrayal of chivalric love in medieval literature.",
    "58. The concept of \"romantic nostalgia.\"",
    "59. The role of love songs in cultural traditions.",
    "60. The influence of Shakespeare on romantic literature.",
    "61. The portrayal of romance in Renaissance art.",
    "62. The concept of \"romantic fatalism.\"",
    "63. The role of romantic rituals in weddings.",
    "64. The impact of romanticism as a literary movement.",
    "65. The portrayal of romantic archetypes in folklore.",
    "66. The concept of \"forbidden love\" in historical contexts.",
    "67. The role of religion in shaping romantic relationships.",
    "68. The influence of Victorian literature on romantic ideals.",
    "69. The portrayal of romance in classical music.",
    "70. The concept of \"tragic love stories.\"",
    "71. The role of romanticism in the 19th century.",
    "72. The impact of cultural revolutions on romantic norms.",
    "73. The portrayal of romance in medieval courtly love.",
    "74. The concept of \"romantic sacrifice.\"",
    "75. The role of romantic poetry in ancient cultures.",
    "76. The influence of romanticism on modern romance.",
    "77. The portrayal of epic love stories in ancient literature.",
    "78. The concept of \"romantic escapism.\"",
    "79. The role of mythology in shaping romantic beliefs.",
    "80. The impact of colonialism on romantic relationships.",
    "81. The portrayal of romance in Gothic literature.",
    "82. The concept of \"romantic idealization\" in different eras.",
    "83. The role of romantic traditions in ancient civilizations.",
    "84. The influence of romantic novels on 20th-century love.",
    "85. The portrayal of romance in Shakespeare's plays.",
    "86. The concept of \"romantic heroism\" in modern literature.",
    "87. The role of historical love letters in understanding past relationships.",
    "88. The impact of cultural diversity on romantic expressions.",
    "89. The portrayal of romance in historical dramas.",
    "90. The concept of \"romantic destiny\" in folklore.",
    "91. The role of storytelling in preserving romantic traditions.",
    "92. The influence of romantic literature on feminist thought.",
    "93. The portrayal of romance in ancient epics.",
    "94. The concept of \"romantic legends\" in various cultures.",
    "95. The role of dance in expressing romantic love.",
    "96. The impact of global events on romantic norms.",
    "97. The portrayal of romance in historical romances.",
    "98. The concept of \"romantic symbolism\" in art.",
    "99. The role of love in ancient philosophical writings.",
    "100. The influence of the Romantic era on contemporary romance.",
]

list2 = [    
    "101. The concept of \"romantic jealousy.\"",
    "102. The role of emotional resilience in relationships.",
    "103. The impact of attachment styles on romantic relationships.",
    "104. The portrayal of emotional abuse in romantic media.",
    "105. The concept of \"love and hate\" dynamics.",
    "106. The role of empathy in romantic relationships.",
    "107. The influence of past relationships on emotional availability.",
    "108. The portrayal of unrequited love in literature and film.",
    "109. The concept of \"romantic infatuation.\"",
    "110. The role of emotional vulnerability in love.",
    "111. The impact of personality types on romantic compatibility.",
    "112. The portrayal of love and loss in media.",
    "113. The concept of \"romantic obsession.\"",
    "114. The role of self-esteem in romantic relationships.",
    "115. The influence of family dynamics on romantic choices.",
    "116. The portrayal of heartbreak in popular culture.",
    "117. The concept of \"emotional baggage\" in relationships.",
    "118. The role of self-discovery in finding love.",
    "119. The impact of childhood trauma on romantic relationships.",
    "120. The portrayal of toxic relationships in media.",
    "121. The concept of \"emotional connection\" in romance.",
    "122. The role of mindfulness in romantic relationships.",
    "123. The influence of psychological disorders on romance.",
    "124. The portrayal of romantic passion in literature.",
    "125. The concept of \"romantic self-sabotage.\"",
    "126. The role of self-awareness in romantic relationships.",
    "127. The impact of fear of intimacy on romantic relationships.",
    "128. The portrayal of love and friendship dynamics in media.",
    "129. The concept of \"romantic idealization vs. reality.\"",
    "130. The role of emotional intelligence in managing relationship conflicts.",
    "131. The influence of cognitive biases on romantic choices.",
    "132. The portrayal of romantic loneliness in literature.",
    "133. The concept of \"romantic curiosity.\"",
    "134. The role of emotional regulation in relationships.",
    "135. The impact of personal growth on romantic relationships.",
    "136. The portrayal of love addiction in media.",
    "137. The concept of \"romantic compatibility.\"",
    "138. The role of gratitude in romantic relationships.",
    "139. The influence of emotional trauma on romantic behavior.",
    "140. The portrayal of love and betrayal in literature and film.",
    "141. The concept of \"romantic fantasy vs. reality.\"",
    "142. The role of self-care in maintaining a healthy relationship.",
    "143. The impact of emotional availability on romantic success.",
    "144. The portrayal of love and redemption in media.",
    "145. The concept of \"emotional intimacy vs. physical intimacy.\"",
    "146. The role of acceptance in romantic relationships.",
    "147. The influence of emotional maturity on relationship longevity.",
    "148. The portrayal of romantic sacrifice in literature and film.",
    "149. The concept of \"romantic regret.\"",
    "150. The role of emotional boundaries in relationships.",
    "",
    "### Romance and Society",
    "151. The role of public displays of affection in different cultures.",
    "152. The influence of romantic ideals on societal norms.",
    "153. The portrayal of romance in fashion and advertising.",
    "154. The concept of \"romantic privacy.\"",
    "155. The role of community in supporting relationships.",
    "156. The impact of economic status on romantic relationships.",
    "157. The portrayal of romance in political contexts.",
    "158. The concept of \"celebrity relationships.\"",
    "159. The role of societal pressure in romantic decision-making.",
    "160. The influence of romantic narratives on social media.",
    "161. The portrayal of romance in the workplace.",
    "162. The concept of \"public vs. private love.\"",
    "163. The role of media in shaping romantic expectations.",
    "164. The impact of cultural festivals on romantic relationships.",
    "165. The portrayal of romance in reality TV.",
    "166. The concept of \"romantic consumerism.\"",
    "167. The role of social expectations in choosing a partner.",
    "168. The influence of romantic stereotypes on behavior.",
    "169. The portrayal of romantic relationships in advertising.",
    "170. The concept of \"love in the age of capitalism.\"",
    "171. The role of public opinion in relationship dynamics.",
    "172. The impact of political ideologies on romantic relationships.",
    "173. The portrayal of romance in sports culture.",
    "174. The concept of \"romantic activism.\"",
    "175. The role of community events in fostering romance.",
    "176. The influence of romantic success stories on society.",
    "177. The portrayal of romance in digital culture.",
    "178. The concept of \"romantic escapades.\"",
    "179. The role of societal norms in defining romantic gestures.",
    "180. The impact of urbanization on romantic relationships.",
    "181. The portrayal of romance in public life.",
    "182. The concept of \"romantic idealization in the media.\"",
    "183. The role of cultural icons in shaping romantic ideals.",
    "184. The influence of romantic comedies on dating behavior.",
    "185. The portrayal of romance in celebrity culture.",
    "186. The concept of \"romantic realism vs. idealism.\"",
    "187. The role of social movements in redefining romance.",
    "188. The impact of globalization on romantic norms.",
    "189. The portrayal of romance in popular music.",
    "190. The concept of \"romantic milestones.\"",
    "191. The role of peer pressure in romantic relationships.",
    "192. The influence of social justice issues on romantic choices.",
    "193. The portrayal of romance in youth culture.",
    "194. The concept of \"romantic independence.\"",
    "195. The role of cultural diversity in romantic relationships.",
    "196. The impact of immigration on romantic relationships.",
    "197. The portrayal of romance in luxury culture.",
    "198. The concept of \"romantic generosity.\"",
    "199. The role of romantic gestures in political campaigns.",
]

list3 = [
    "200. The influence of social media influencers on romantic ideals.",       
    "201. The role of romantic symbolism in visual art.",
    "202. The portrayal of love in animated films.",
    "203. The concept of \"romantic escapism in literature.\"",
    "204. The role of love letters in literature and history.",
    "205. The influence of romantic themes in modern music.",
    "206. The portrayal of romance in television dramas.",
    "207. The concept of \"romantic subtext\" in storytelling.",
    "208. The role of romantic imagery in film.",
    "209. The impact of visual novels on romantic storytelling.",
    "210. The portrayal of romance in soap operas.",
    "211. The concept of \"romantic motifs\" in literature.",
    "212. The role of romantic relationships in reality TV.",
    "213. The influence of romantic fanfiction on pop culture.",
    "214. The portrayal of romance in superhero comics.",
    "215. The concept of \"romanticized history\" in film.",
    "216. The role of romantic clichés in media.",
    "217. The impact of romantic soundtracks on film and TV.",
    "218. The portrayal of romance in anime and manga.",
    "219. The concept of \"romantic arcs\" in TV series.",
    "220. The role of romantic suspense in thriller novels.",
    "221. The influence of romantic photography on art.",
    "222. The portrayal of romantic reunions in media.",
    "223. The concept of \"romantic comedy tropes.\"",
    "224. The role of romance in classic literature adaptations.",
    "225. The impact of romantic dance scenes in film.",
    "226. The portrayal of romance in fantasy literature.",
    "227. The concept of \"romantic plot devices.\"",
    "228. The role of romantic relationships in soap operas.",
    "229. The influence of romantic dialogue in classic films.",
    "230. The portrayal of epic romances in cinema.",
    "231. The concept of \"romantic nostalgia\" in media.",
    "232. The role of romantic subplots in action films.",
    "233. The impact of romantic tragedies in literature.",
    "234. The portrayal of romance in dystopian stories.",
    "235. The concept of \"romantic resolutions\" in fiction.",
    "236. The role of romantic rivalry in storytelling.",
    "237. The influence of romantic metaphors in poetry.",
    "238. The portrayal of forbidden love in popular culture.",
    "239. The concept of \"romantic idealization\" in movies.",
    "240. The role of romantic backdrops in cinema.",
    "241. The impact of romantic melodrama in television.",
    "242. The portrayal of romance in video games.",
    "243. The concept of \"romantic tropes\" in literature.",
    "244. The role of romantic chemistry in film casting.",
    "245. The influence of romantic classics on contemporary storytelling.",
    "246. The portrayal of romance in fantasy TV series.",
    "247. The concept of \"romantic settings\" in novels.",
    "248. The role of romantic protagonists in literature.",
    "249. The impact of romantic themes in Broadway musicals.",
    "250. The portrayal of love and adventure in media.",    
    "251. The concept of \"romantic fatalism.\"",
    "252. The role of existentialism in romantic thought.",
    "253. The impact of philosophical theories on love.",
    "254. The portrayal of romantic ideals in philosophical writings.",
    "255. The concept of \"romantic skepticism.\"",
    "256. The role of romanticism in existential literature.",
    "257. The influence of Platonic love on Western philosophy.",
    "258. The portrayal of romantic philosophy in classic literature.",
    "259. The concept of \"romantic idealism vs. realism.\"",
    "260. The role of love in ancient Greek philosophy.",
    "261. The impact of romanticism on modern philosophy.",
    "262. The portrayal of romantic ideals in Eastern philosophy.",
    "263. The concept of \"romantic transcendence.\"",
    "264. The role of love in existential philosophy.",
    "265. The influence of romantic ethics on personal relationships.",
    "266. The portrayal of romantic relationships in philosophical discourse.",
    "267. The concept of \"romantic nihilism.\"",
    "268. The role of romanticism in shaping cultural narratives.",
    "269. The impact of philosophical romanticism on literature.",
    "270. The portrayal of romantic ideals in philosophical essays.",
    "271. The concept of \"romantic authenticity.\"",
    "272. The role of love in religious philosophy.",
    "273. The influence of romantic philosophy on art.",
    "274. The portrayal of romantic ideals in Renaissance philosophy.",
    "275. The concept of \"romantic dualism.\"",
    "276. The role of romanticism in the Enlightenment.",
    "277. The impact of romanticism on political philosophy.",
    "278. The portrayal of romantic ideals in existentialist literature.",
    "279. The concept of \"romantic metaphysics.\"",
    "280. The role of romanticism in shaping modern thought.",
    "281. The influence of romantic philosophy on ethics.",
    "282. The portrayal of romantic ideals in medieval philosophy.",
    "283. The concept of \"romantic realism.\"",
    "284. The role of romanticism in feminist philosophy.",
    "285. The impact of romantic ideals on moral philosophy.",
    "286. The portrayal of love in philosophical novels.",
    "287. The concept of \"romantic subjectivity.\"",
    "288. The role of romanticism in shaping cultural identity.",
    "289. The influence of romantic philosophy on psychology.",
    "290. The portrayal of romantic ideals in political philosophy.",
    "291. The concept of \"romantic determinism.\"",
    "292. The role of romanticism in shaping artistic movements.",
    "293. The impact of romantic ideals on cultural theory.",
    "294. The portrayal of romantic ideals in postmodern philosophy.",
    "295. The concept of \"romantic epistemology.\"",
    "296. The role of romanticism in the development of aesthetics.",
    "297. The influence of romantic ideals on human rights discourse.",
    "298. The portrayal of romanticism in philosophical biographies.",
    "299. The concept of \"romantic idealization in thought.\"",
    "300. The role of romantic philosophy in shaping contemporary culture.",    
]


from random import choice
all = list1 + list2 + list3
def get_romance_topic():
    return choice(all)