list1 = [
    "Quantum mechanics",
    "Theory of relativity",
    "Evolutionary biology",
    "Genetic engineering",
    "Neuroscience",
    "Artificial intelligence",
    "Renewable energy",
    "Climate change",
    "Biotechnology",
    "Nanotechnology",
    "Marine biology",
    "Space exploration",
    "Particle physics",
    "Molecular biology",
    "CRISPR technology",
    "Human genome project",
    "Renewable energy technologies",
    "Environmental science",
    "Computational biology",
    "The scientific method",
    "Science communication",
    "Science education",
    "Scientific research methods",
    "Scientific innovation",
    "Science policy",
    "Citizen science",
    "History of science",
    "Philosophy of science",
    "Science and society",
    "Women in science",
    "Scientific discoveries",
    "Science and technology studies",
    "Science fiction and science",
    "Science in popular culture",
    "Scientific ethics",
    "Science and religion",
    "Science and pseudoscience",
    "Science journalism",
    "Science museums",
    "Science festivals",
    "Science and art",
    "Science and literature",
    "Science and politics",
    "Science funding",
    "Science careers",
    "Science outreach",
    "Science communication strategies",
    "Science in the media",
    "Science and industry",
    "Science and innovation policies",
    "Physics",
    "Classical mechanics",
    "Electromagnetism",
    "Thermodynamics",
    "Statistical mechanics",
    "Quantum field theory",
    "General relativity",
    "Special relativity",
    "Condensed matter physics",
    "Nuclear physics",
    "Plasma physics",
    "Atomic physics",
    "Optics",
    "Acoustics",
    "Solid-state physics",
    "Quantum computing",
    "Quantum entanglement",
    "Superconductivity",
    "Bose-Einstein condensates",
    "String theory",
    "Quantum chromodynamics",
    "Quantum gravity",
    "Dark matter",
    "Dark energy",
    "Higgs boson",
    "Large Hadron Collider",
    "Particle accelerators",
    "Cosmic microwave background",
    "Black holes",
    "Neutron stars",
    "White dwarfs",
    "Gravitational waves",
    "Cosmology",
    "Astrophysics",
    "Exoplanets",
    "Stellar evolution",
    "Galaxy formation",
    "Big Bang theory",
    "Multiverse theory",
    "Time travel",
    "Wormholes",
    "Quantum mechanics interpretations",
    "Heisenberg uncertainty principle",
    "Schrödinger's cat",
    "Wave-particle duality",
    "Quantum tunneling",
    "Quantum superposition",
    "Quantum teleportation",
    "Quantum cryptography",
    "Quantum optics",
    "Quantum information theory",
    "Universe",
    "The origin of the universe",
    "The fate of the universe",
    "The structure of the universe",
    "The observable universe",
    "The expanding universe",
    "The cosmic web",
    "The cosmic horizon",
    "The cosmic microwave background radiation",
    "The cosmic inflation theory",
    "The cosmic distance ladder",
    "The cosmic scale",
    "The cosmic calendar",
    "The cosmic background explorer (COBE)",
    "The cosmic neutrino background",
    "The cosmic voids",
    "The cosmic rays",
    "The cosmic radiation",
    "The cosmic microwave background polarization",
    "The cosmic censorship hypothesis",
    "The cosmic coincidences",
    "The cosmic evolution",
    "The cosmic nucleosynthesis",
    "The cosmic reionization",
    "The cosmic sound waves",
    "The cosmic strings",
    "The cosmic time",
    "The cosmic vision",
    "The cosmic web filaments",
    "The cosmic yardstick",
    "The multiverse theory",
    "The parallel universes",
    "The alternate realities",
    "The bubble universes",
    "The higher dimensions",
    "The brane worlds",
    "The wormholes",
    "The white holes",
    "The event horizon",
    "The singularity",
    "The black hole evaporation",
    "The black hole information paradox",
    "The Hawking radiation",
    "The black hole thermodynamics",
    "The black hole entropy",
    "The black hole merger",
    "The black hole spin",
    "The black hole mass",
    "The black hole formation",
    "The black hole growth",
    "The black hole jets",
    "The neutron stars",
    "The pulsars",
    "The magnetars",
    "The supernovae",
    "The hypernovae",
    "The gamma-ray bursts",
    "The kilonovae",
    "The quasars",
    "The blazars",
    "The active galactic nuclei",
    "The galaxy clusters",
    "The galaxy superclusters",
    "The galaxy mergers",
    "The galaxy interactions",
    "The galaxy evolution",
]

list2 = [
    "The galaxy formation",
    "The spiral galaxies",
    "The elliptical galaxies",
    "The irregular galaxies",
    "The dwarf galaxies",
    "The satellite galaxies",
    "The Milky Way galaxy",
    "The Andromeda galaxy",
    "The Local Group",
    "The Virgo Cluster",
    "The Laniakea Supercluster",
    "The Great Attractor",
    "The Sloan Great Wall",
    "The Hercules-Corona Borealis Great Wall",
    "The Sloan Digital Sky Survey",
    "The Hubble Space Telescope",
    "The James Webb Space Telescope",
    "The Chandra X-ray Observatory",
    "The Spitzer Space Telescope",
    "The Kepler Space Telescope",
    "The Gaia Space Observatory",
    "The Planck Space Observatory",
    "The WMAP Space Observatory",
    "The Herschel Space Observatory",
    "The ALMA Observatory",
    "The VLA Observatory",
    "The Very Large Telescope (VLT)",
    "The Thirty Meter Telescope (TMT)",
    "The Giant Magellan Telescope (GMT)",
    "The Extremely Large Telescope (ELT)",
    "The Square Kilometer Array (SKA)",
    "The Event Horizon Telescope (EHT)",
    "The Laser Interferometer Gravitational-Wave Observatory (LIGO)",
    "The Virgo Interferometer",
    "The KAGRA Interferometer",
    "Astrophysics",
    "Stellar astrophysics",
    "Galactic astrophysics",
    "Extragalactic astrophysics",
    "Observational astrophysics",
    "Theoretical astrophysics",
    "High-energy astrophysics",
    "Cosmological astrophysics",
    "Computational astrophysics",
    "Astrophysical jets",
    "Astrophysical magnetic fields",
    "Astrophysical neutrinos",
    "Astrophysical plasmas",
    "Astrophysical shocks",
    "Astrophysical turbulence",
    "Astrophysical radiation",
    "Astrophysical particles",
    "Astrophysical processes",
    "Astrophysical phenomena",
    "Astrophysical observations",
    "Astrophysical simulations",
    "Astrophysical models",
    "Astrophysical data analysis",
    "Astrophysical instrumentation",
    "Astrophysical missions",
    "Astrophysical discoveries",
    "Astrophysical theories",
    "Astrophysical research",
    "Astrophysical conferences",
    "Astrophysical journals",
    "Astrophysical collaborations",
    "Astrophysical outreach",
    "Astrophysical education",
    "Astrophysical careers",
    "Astrophysical history",
    "Astrophysical societies",
    "Astrophysical awards",
    "Astrophysical challenges",
    "Astrophysical mysteries",
    "Astrophysical breakthroughs",
    "Astrophysical future",
    "Astrophysical advancements",
    "Astrophysical insights",
    "Astrophysical impacts",
    "Astrophysical implications",
    "Astrophysical applications",
    "Astrophysical explorations",
    "Astrophysical technologies",
    "Astrophysical experiments",
    "Astrophysical measurements",
    "Astrophysical interpretations",
    "Astrophysical puzzles",
    "Astrophysical questions",
    "Astrophysical solutions",
    "Astrophysical trends",
    "Astrophysical developments",
    "Astrophysical innovations",
    "Astrophysical potentials",
    "Astrophysical opportunities",
    "Astrophysical strategies",
    "Astrophysical goals",
    "Astrophysical objectives",
    "Astrophysical priorities",
    "Astrophysical perspectives",
    "Astrophysical viewpoints",
    "Astrophysical opinions",
    "Astrophysical reviews",
    "Astrophysical critiques",
    "Astrophysical debates",
    "Astrophysical discussions",
    "Astrophysical analyses",
    "Astrophysical reports",
    "Astrophysical papers",
    "Astrophysical publications",
    "Astrophysical findings",
    "Astrophysical results",
    "Astrophysical data",
    "Astrophysical charts",
    "Astrophysical graphs",
    "Astrophysical tables",
    "Astrophysical figures",
    "Astrophysical illustrations",
    "Astrophysical diagrams",
    "Astrophysical images",
    "Astrophysical maps",
    "Astrophysical models",
    "Astrophysical algorithms",
    "Astrophysical codes",
    "Astrophysical software",
    "Astrophysical tools",
    "Astrophysical equipment",
    "Astrophysical facilities",
    "Astrophysical observatories",
    "Astrophysical telescopes",
    "Astrophysical satellites",
    "Astrophysical probes",
    "Astrophysical rovers",
    "Astrophysical landers",
    "Astrophysical orbiters",
    "Astrophysical missions",
    "Astrophysical collaborations",
    "Astrophysical partnerships",
    "Astrophysical alliances",
    "Astrophysical initiatives",
    "Astrophysical programs",
    "Astrophysical projects",
    "Astrophysical activities",
    "Astrophysical endeavors",
    "Astrophysical ventures",
    "Astrophysical enterprises",
    "Astrophysical undertakings",
    "Astrophysical tasks",
    "Astrophysical duties",
    "Astrophysical responsibilities",
    "Astrophysical roles",
    "Astrophysical contributions",
    "Astrophysical involvement",
    "Astrophysical participation",
    "Astrophysical engagement",
    "Astrophysical cooperation",
    "Astrophysical assistance",
    "Astrophysical support",
    "Astrophysical backing",
    "Astrophysical funding",
    "Astrophysical sponsorship",
    "Astrophysical investment",
    "Astrophysical financing",
    "Astrophysical resources",
    "Astrophysical materials",
    "Astrophysical supplies",
    "Astrophysical provisions",
    "Astrophysical equipment",
]

list3 = [
    "Astrophysical instruments",
    "Astrophysical apparatus",
    "Astrophysical devices",
    "Astrophysical machines",
    "Astrophysical systems",
    "Astrophysical technologies",
    "Astrophysical innovations",
    "Astrophysical inventions",
    "Astrophysical patents",
    "Astrophysical designs",
    "Astrophysical prototypes",
    "Astrophysical models",
    "Astrophysical simulations",
    "Astrophysical experiments",
    "Astrophysical tests",
    "Astrophysical trials",
    "Astrophysical evaluations",
    "Astrophysical assessments",
    "Astrophysical reviews",
    "Astrophysical analyses",
    "Astrophysical examinations",
    "Astrophysical investigations",
    "Astrophysical inspections",
    "Astrophysical observations",
    "Astrophysical measurements",
    "Astrophysical recordings",
    "Astrophysical detections",
    "Astrophysical identifications",
    "Astrophysical classifications",
    "Astrophysical categorizations",
    "Astrophysical organizations",
    "Astrophysical arrangements",
    "Astrophysical systems",
    "Astrophysical structures",
    "Astrophysical frameworks",
    "Astrophysical formats",
    "Astrophysical patterns",
    "Astrophysical sequences",
    "Astrophysical progressions",
    "Astrophysical cycles",
    "Astrophysical phases",
    "Astrophysical stages",
    "Astrophysical steps",
    "Astrophysical processes",
    "Astrophysical procedures",
    "Astrophysical methods",
    "Astrophysical techniques",
    "Astrophysical strategies",
    "Astrophysical plans",
    "Astrophysical schemes",
    "Astrophysical blueprints",
    "Astrophysical roadmaps",
    "Astrophysical guides",
    "Astrophysical manuals",
    "Astrophysical handbooks",
    "Astrophysical textbooks",
    "Astrophysical courses",
    "Astrophysical lectures",
    "Astrophysical presentations",
    "Astrophysical seminars",
    "Astrophysical workshops",
    "Astrophysical conferences",
    "Astrophysical symposiums",
    "Astrophysical meetings",
    "Astrophysical sessions",
    "Astrophysical discussions",
    "Astrophysical debates",
    "Astrophysical dialogues",
    "Astrophysical conversations",
    "Astrophysical interactions",
    "Astrophysical communications",
    "Astrophysical correspondences",
    "Astrophysical exchanges",
    "Astrophysical transmissions",
    "Astrophysical broadcasts",
    "Astrophysical publications",
    "Astrophysical journals",
    "Astrophysical articles",
    "Astrophysical papers",
    "Astrophysical reports",
    "Astrophysical reviews",
    "Astrophysical summaries",
    "Astrophysical abstracts",
    "Astrophysical conclusions",
    "Astrophysical findings",
    "Astrophysical results",
    "Astrophysical outcomes",
    "Astrophysical impacts",
    "Astrophysical effects",
    "Astrophysical implications",
    "Astrophysical significance",
    "Astrophysical relevance",
    "Astrophysical importance",
    "Astrophysical value",
    "Astrophysical utility",
    "Astrophysical applications",
    "Astrophysical uses",
    "Astrophysical benefits",
    "Astrophysical advantages",
    "Astrophysical strengths",
    "Astrophysical merits",
    "Astrophysical attributes",
    "Astrophysical qualities",
    "Astrophysical features",
    "Astrophysical characteristics",
    "Astrophysical properties",
    "Astrophysical aspects",
    "Astrophysical components",
    "Astrophysical elements",
    "Astrophysical parts",
    "Astrophysical pieces",
    "Astrophysical factors",
    "Astrophysical variables",
    "Astrophysical parameters",
    "Astrophysical dimensions",
    "Astrophysical magnitudes",
    "Astrophysical scales",
    "Astrophysical levels",
    "Astrophysical degrees",
    "Astrophysical ranges",
    "Astrophysical spectra",
    "Astrophysical frequencies",
    "Astrophysical wavelengths",
    "Astrophysical amplitudes",
    "Astrophysical intensities",
    "Astrophysical powers",
    "Astrophysical energies",
    "Astrophysical forces",
    "Astrophysical fields",
    "Astrophysical currents",
    "Astrophysical fluxes",
    "Astrophysical densities",
    "Astrophysical masses",
    "Astrophysical volumes",
    "Astrophysical pressures",
    "Astrophysical temperatures",
    "Astrophysical velocities",
    "Astrophysical speeds",
    "Astrophysical accelerations",
    "Astrophysical motions",
    "Astrophysical rotations",
    "Astrophysical revolutions",
    "Astrophysical orbits",
    "Astrophysical trajectories",
    "Astrophysical paths",
    "Astrophysical directions",
    "Astrophysical positions",
    "Astrophysical locations",
    "Astrophysical distances",
    "Astrophysical coordinates",
    "Astrophysical angles",
    "Astrophysical inclinations",
    "Astrophysical orientations",
    "Astrophysical alignments",
    "Astrophysical formations",
    "Astrophysical arrangements",
    "Astrophysical configurations",
    "Astrophysical systems",
    "Astrophysical networks",
    "Astrophysical connections",
    "Astrophysical relationships",
    "Astrophysical interactions",
    "Astrophysical collaborations",
    "Astrophysical partnerships",
    "Astrophysical alliances",
    "Astrophysical associations",
    "Astrophysical unions",
    "Astrophysical federations",
    "Astrophysical communities",
]

from random import choice
all = list1 + list2 + list3
def get_science_topic():
    return choice(all)


